### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by aimansae** [aimansae/reviewme#16]
As a **user** I can **edit my profile** so that **I can change my information**

**ACCEPTANCE CRITERIA**: 
- 

**TASKS:**

- [ ] .show a dropdown if current user is the owner of the profile
- [ ] show form to modify data, prefilled with the existing data
- [ ]  update the page with the new/ modified data
