### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by aimansae** [aimansae/reviewme#2]
As a **user** I can **login** so that **I can access the content for logged users**

**ACCEPTANCE CRITERIA**: 
- show login page correcty
- upon login redirect user to homepage
- navbar shows features for logged in users

**TASKS:**

- [x]  login button and form
- [x]  home page visible correctly
- [x]  navbar updates correctly
